name: Run Laravel Pint

on:
  push:
    paths:
      - '**.php'
      - 'phpunit.xml'
      - '.github/workflows/code-style.yml'
      - 'composer.lock'

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: xdebug

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install PHP Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Execute code style rules
      run: vendor/bin/pint --test
