name: Run test PHPUnit

on:
  push:
    paths:
      - '**.php'
      - 'phpunit.xml'
      - '.github/workflows/tests.yml'
      - 'composer.lock'

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: xdebug

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install PHP Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Install JavaScript Dependencies
      run: npm install --production

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Fix code coverage paths
      run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml
